# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'layouts/main_window.ui'
#
# Created: Sat Dec 15 14:13:33 2012
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!
from PyQt4 import QtCore, QtGui
from os.path import dirname
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(857, 591)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setOpaqueResize(False)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.listWidget = QtGui.QListWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(7)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.repositoryTableWidget = QtGui.QTableWidget(self.splitter)
        self.repositoryTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.repositoryTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.repositoryTableWidget.setObjectName(_fromUtf8("repositoryTableWidget"))
        self.repositoryTableWidget.setColumnCount(5)
        self.repositoryTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(4, item)
        self.bottomwidgets = QtGui.QStackedWidget(self.splitter)
        self.bottomwidgets.setObjectName(_fromUtf8("bottomwidgets"))
        self.Page1 = QtGui.QWidget()
        self.Page1.setObjectName(_fromUtf8("Page1"))
        self.changesetLayout = QtGui.QHBoxLayout(self.Page1)
        self.changesetLayout.setObjectName(_fromUtf8("changesetLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.changesetButtonsLayout = QtGui.QVBoxLayout()
        self.changesetButtonsLayout.setObjectName(_fromUtf8("changesetButtonsLayout"))
        self.stageButton = QtGui.QPushButton(self.Page1)
        self.stageButton.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/stage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stageButton.setIcon(icon)
        self.stageButton.setObjectName(_fromUtf8("stageButton"))
        self.changesetButtonsLayout.addWidget(self.stageButton)
        self.unstageButton = QtGui.QPushButton(self.Page1)
        self.unstageButton.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/unstage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unstageButton.setIcon(icon1)
        self.unstageButton.setObjectName(_fromUtf8("unstageButton"))
        self.changesetButtonsLayout.addWidget(self.unstageButton)
        self.discardButton = QtGui.QPushButton(self.Page1)
        self.discardButton.setEnabled(False)
        self.discardButton.setObjectName(_fromUtf8("discardButton"))
        self.changesetButtonsLayout.addWidget(self.discardButton)
        self.separator = QtGui.QFrame(self.Page1)
        self.separator.setFrameShape(QtGui.QFrame.HLine)
        self.separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.separator.setObjectName(_fromUtf8("separator"))
        self.changesetButtonsLayout.addWidget(self.separator)
        self.pullButton = QtGui.QPushButton(self.Page1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/pull.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pullButton.setIcon(icon2)
        self.pullButton.setObjectName(_fromUtf8("pullButton"))
        self.changesetButtonsLayout.addWidget(self.pullButton)
        self.commitButton = QtGui.QPushButton(self.Page1)
        self.commitButton.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/commit_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commitButton.setIcon(icon3)
        self.commitButton.setObjectName(_fromUtf8("commitButton"))
        self.changesetButtonsLayout.addWidget(self.commitButton)
        self.stashButton = QtGui.QPushButton(self.Page1)
        self.stashButton.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/stash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stashButton.setIcon(icon4)
        self.stashButton.setObjectName(_fromUtf8("stashButton"))
        self.changesetButtonsLayout.addWidget(self.stashButton)
        self.pushButton = QtGui.QPushButton(self.Page1)
        self.pushButton.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/push.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.changesetButtonsLayout.addWidget(self.pushButton)
        self.horizontalLayout_4.addLayout(self.changesetButtonsLayout)
        self.files_listWidget = QtGui.QListWidget(self.Page1)
        self.files_listWidget.setObjectName(_fromUtf8("files_listWidget"))
        self.horizontalLayout_4.addWidget(self.files_listWidget)
        self.diff_textBrowser = QtGui.QTextBrowser(self.Page1)
        self.diff_textBrowser.setObjectName(_fromUtf8("diff_textBrowser"))
        self.horizontalLayout_4.addWidget(self.diff_textBrowser)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 3)
        self.changesetLayout.addLayout(self.horizontalLayout_4)
        self.bottomwidgets.addWidget(self.Page1)
        self.Page2 = QtGui.QWidget()
        self.Page2.setEnabled(True)
        self.Page2.setObjectName(_fromUtf8("Page2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.Page2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.changesetButtonsLayout_2 = QtGui.QVBoxLayout()
        self.changesetButtonsLayout_2.setObjectName(_fromUtf8("changesetButtonsLayout_2"))
        self.stageButton_2 = QtGui.QPushButton(self.Page2)
        self.stageButton_2.setEnabled(True)
        self.stageButton_2.setIcon(icon)
        self.stageButton_2.setObjectName(_fromUtf8("stageButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.stageButton_2)
        self.unstageButton_2 = QtGui.QPushButton(self.Page2)
        self.unstageButton_2.setEnabled(True)
        self.unstageButton_2.setIcon(icon1)
        self.unstageButton_2.setObjectName(_fromUtf8("unstageButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.unstageButton_2)
        self.discardButton_2 = QtGui.QPushButton(self.Page2)
        self.discardButton_2.setObjectName(_fromUtf8("discardButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.discardButton_2)
        self.separator_2 = QtGui.QFrame(self.Page2)
        self.separator_2.setFrameShape(QtGui.QFrame.HLine)
        self.separator_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.separator_2.setObjectName(_fromUtf8("separator_2"))
        self.changesetButtonsLayout_2.addWidget(self.separator_2)
        self.pullButton_2 = QtGui.QPushButton(self.Page2)
        self.pullButton_2.setIcon(icon2)
        self.pullButton_2.setObjectName(_fromUtf8("pullButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.pullButton_2)
        self.commitButton_2 = QtGui.QPushButton(self.Page2)
        self.commitButton_2.setEnabled(True)
        self.commitButton_2.setIcon(icon3)
        self.commitButton_2.setObjectName(_fromUtf8("commitButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.commitButton_2)
        self.stashButton_2 = QtGui.QPushButton(self.Page2)
        self.stashButton_2.setIcon(icon4)
        self.stashButton_2.setObjectName(_fromUtf8("stashButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.stashButton_2)
        self.pushButton_2 = QtGui.QPushButton(self.Page2)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addLayout(self.changesetButtonsLayout_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_3 = QtGui.QLabel(self.Page2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.commit_lineEdit = QtGui.QLineEdit(self.Page2)
        self.commit_lineEdit.setObjectName(_fromUtf8("commit_lineEdit"))
        self.horizontalLayout_9.addWidget(self.commit_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.amendCheckBox = QtGui.QCheckBox(self.Page2)
        self.amendCheckBox.setObjectName(_fromUtf8("amendCheckBox"))
        self.verticalLayout_2.addWidget(self.amendCheckBox)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.Page2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.Unstaged_listwidget = QtGui.QListWidget(self.Page2)
        self.Unstaged_listwidget.setObjectName(_fromUtf8("Unstaged_listwidget"))
        self.verticalLayout_5.addWidget(self.Unstaged_listwidget)
        self.label_6 = QtGui.QLabel(self.Page2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.Staged_listWidget = QtGui.QListWidget(self.Page2)
        self.Staged_listWidget.setObjectName(_fromUtf8("Staged_listWidget"))
        self.verticalLayout_5.addWidget(self.Staged_listWidget)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.Page2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.diff_local_textBrowser = QtGui.QTextBrowser(self.Page2)
        self.diff_local_textBrowser.setObjectName(_fromUtf8("diff_local_textBrowser"))
        self.verticalLayout_4.addWidget(self.diff_local_textBrowser)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.bottomwidgets.addWidget(self.Page2)
        self.horizontalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuRepository = QtGui.QMenu(self.menubar)
        self.menuRepository.setObjectName(_fromUtf8("menuRepository"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionClone_repository = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/clone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClone_repository.setIcon(icon6)
        self.actionClone_repository.setObjectName(_fromUtf8("actionClone_repository"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon7)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionAbout_PyGitGui = QtGui.QAction(MainWindow)
        self.actionAbout_PyGitGui.setObjectName(_fromUtf8("actionAbout_PyGitGui"))
        self.actionPull = QtGui.QAction(MainWindow)
        self.actionPull.setIcon(icon2)
        self.actionPull.setObjectName(_fromUtf8("actionPull"))
        self.actionAdd_files = QtGui.QAction(MainWindow)
        self.actionAdd_files.setObjectName(_fromUtf8("actionAdd_files"))
        self.actionRemove_files = QtGui.QAction(MainWindow)
        self.actionRemove_files.setObjectName(_fromUtf8("actionRemove_files"))
        self.actionCommit = QtGui.QAction(MainWindow)
        self.actionCommit.setIcon(icon3)
        self.actionCommit.setObjectName(_fromUtf8("actionCommit"))
        self.actionPush = QtGui.QAction(MainWindow)
        self.actionPush.setIcon(icon5)
        self.actionPush.setObjectName(_fromUtf8("actionPush"))
        self.actionChange_branch = QtGui.QAction(MainWindow)
        self.actionChange_branch.setObjectName(_fromUtf8("actionChange_branch"))
        self.actionCherry_pick = QtGui.QAction(MainWindow)
        self.actionCherry_pick.setObjectName(_fromUtf8("actionCherry_pick"))
        self.actionClone_repository_2 = QtGui.QAction(MainWindow)
        self.actionClone_repository_2.setIcon(icon6)
        self.actionClone_repository_2.setObjectName(_fromUtf8("actionClone_repository_2"))
        self.actionAdd_existing_repository = QtGui.QAction(MainWindow)
        self.actionAdd_existing_repository.setIcon(icon)
        self.actionAdd_existing_repository.setObjectName(_fromUtf8("actionAdd_existing_repository"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon8)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionAbout_Gitraffe = QtGui.QAction(MainWindow)
        self.actionAbout_Gitraffe.setObjectName(_fromUtf8("actionAbout_Gitraffe"))
        self.actionClone_repository_3 = QtGui.QAction(MainWindow)
        self.actionClone_repository_3.setIcon(icon6)
        self.actionClone_repository_3.setObjectName(_fromUtf8("actionClone_repository_3"))
        self.actionAdd_existing_repository_2 = QtGui.QAction(MainWindow)
        self.actionAdd_existing_repository_2.setIcon(icon)
        self.actionAdd_existing_repository_2.setObjectName(_fromUtf8("actionAdd_existing_repository_2"))
        self.actionStash = QtGui.QAction(MainWindow)
        self.actionStash.setIcon(icon4)
        self.actionStash.setObjectName(_fromUtf8("actionStash"))
        self.actionDelete_repository = QtGui.QAction(MainWindow)
        self.actionDelete_repository.setIcon(icon1)
        self.actionDelete_repository.setObjectName(_fromUtf8("actionDelete_repository"))
        self.actionDelete_branch = QtGui.QAction(MainWindow)
        self.actionDelete_branch.setObjectName(_fromUtf8("actionDelete_branch"))
        self.actionCreate_branch = QtGui.QAction(MainWindow)
        self.actionCreate_branch.setObjectName(_fromUtf8("actionCreate_branch"))
        self.actionStashes = QtGui.QAction(MainWindow)
        self.actionStashes.setObjectName(_fromUtf8("actionStashes"))
        self.menuFile.addAction(self.actionClone_repository_2)
        self.menuFile.addAction(self.actionAdd_existing_repository)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionRefresh)
        self.menuRepository.addAction(self.actionPull)
        self.menuRepository.addAction(self.actionPush)
        self.menuRepository.addSeparator()
        self.menuRepository.addAction(self.actionStashes)
        self.menuRepository.addSeparator()
        self.menuRepository.addAction(self.actionChange_branch)
        self.menuRepository.addAction(self.actionDelete_branch)
        self.menuRepository.addAction(self.actionCreate_branch)
        self.menuHelp.addAction(self.actionAbout_Gitraffe)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuRepository.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionClone_repository_3)
        self.toolBar.addAction(self.actionAdd_existing_repository_2)
        self.toolBar.addAction(self.actionDelete_repository)
        self.retranslateUi(MainWindow)
        self.bottomwidgets.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Gitraffe", None))
        item = self.repositoryTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Commit", None))
        item = self.repositoryTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Message", None))
        item = self.repositoryTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Author", None))
        item = self.repositoryTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date", None))
        self.stageButton.setText(_translate("MainWindow", "Stage", None))
        self.unstageButton.setText(_translate("MainWindow", "Unstage", None))
        self.discardButton.setText(_translate("MainWindow", "Discard", None))
        self.pullButton.setText(_translate("MainWindow", "Pull", None))
        self.commitButton.setText(_translate("MainWindow", " Commit", None))
        self.stashButton.setText(_translate("MainWindow", "Stash", None))
        self.pushButton.setText(_translate("MainWindow", "Push", None))
        self.stageButton_2.setText(_translate("MainWindow", "Stage", None))
        self.unstageButton_2.setText(_translate("MainWindow", "Unstage", None))
        self.discardButton_2.setText(_translate("MainWindow", "Discard", None))
        self.pullButton_2.setText(_translate("MainWindow", "Pull", None))
        self.commitButton_2.setText(_translate("MainWindow", " Commit", None))
        self.stashButton_2.setText(_translate("MainWindow", "Stash", None))
        self.pushButton_2.setText(_translate("MainWindow", "Push", None))
        self.label_3.setText(_translate("MainWindow", "Commit message:", None))
        self.amendCheckBox.setText(_translate("MainWindow", "Amend commit", None))
        self.label_5.setText(_translate("MainWindow", "Unstaged:", None))
        self.label_6.setText(_translate("MainWindow", "Staged:", None))
        self.label_4.setText(_translate("MainWindow", "Diff:", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuRepository.setTitle(_translate("MainWindow", "Repository", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionClone_repository.setText(_translate("MainWindow", "Clone repository...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.actionAbout_PyGitGui.setText(_translate("MainWindow", "About PyGitGui", None))
        self.actionPull.setText(_translate("MainWindow", "Pull", None))
        self.actionAdd_files.setText(_translate("MainWindow", "Add files...", None))
        self.actionRemove_files.setText(_translate("MainWindow", "Remove files...", None))
        self.actionCommit.setText(_translate("MainWindow", "Commit", None))
        self.actionPush.setText(_translate("MainWindow", "Push", None))
        self.actionChange_branch.setText(_translate("MainWindow", "Change branch", None))
        self.actionCherry_pick.setText(_translate("MainWindow", "Cherry-pick", None))
        self.actionClone_repository_2.setText(_translate("MainWindow", "Clone repository...", None))
        self.actionAdd_existing_repository.setText(_translate("MainWindow", "Add existing repository...", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionAbout_Gitraffe.setText(_translate("MainWindow", "About Gitraffe", None))
        self.actionClone_repository_3.setText(_translate("MainWindow", "Clone repository...", None))
        self.actionAdd_existing_repository_2.setText(_translate("MainWindow", "Add existing repository", None))
        self.actionStash.setText(_translate("MainWindow", "Stash", None))
        self.actionDelete_repository.setText(_translate("MainWindow", "Delete repository", None))
        self.actionDelete_branch.setText(_translate("MainWindow", "Delete branch", None))
        self.actionCreate_branch.setText(_translate("MainWindow", "Create branch", None))
        self.actionStashes.setText(_translate("MainWindow", "Stashes", None))
