# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Thu Sep 27 22:11:52 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from os.path import dirname

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(857, 591)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.horizontalLayout.addWidget(self.listWidget)
        self.repositoryLayout = QtGui.QVBoxLayout()
        self.repositoryLayout.setObjectName(_fromUtf8("repositoryLayout"))
        self.repositoryTableWidget = QtGui.QTableWidget(self.centralwidget)
        self.repositoryTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.repositoryTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.repositoryTableWidget.setObjectName(_fromUtf8("repositoryTableWidget"))
        self.repositoryTableWidget.setColumnCount(5)
        self.repositoryTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.repositoryTableWidget.setHorizontalHeaderItem(4, item)
        self.repositoryLayout.addWidget(self.repositoryTableWidget)
        self.bottomwidgets = QtGui.QStackedWidget(self.centralwidget)
        self.bottomwidgets.setObjectName(_fromUtf8("bottomwidgets"))
        self.Page1 = QtGui.QWidget()
        self.Page1.setObjectName(_fromUtf8("Page1"))
        self.changesetLayout = QtGui.QHBoxLayout(self.Page1)
        self.changesetLayout.setObjectName(_fromUtf8("changesetLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.changesetButtonsLayout = QtGui.QVBoxLayout()
        self.changesetButtonsLayout.setObjectName(_fromUtf8("changesetButtonsLayout"))
        self.stageButton = QtGui.QPushButton(self.Page1)
        self.stageButton.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/stage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stageButton.setIcon(icon)
        self.stageButton.setObjectName(_fromUtf8("stageButton"))
        self.changesetButtonsLayout.addWidget(self.stageButton)
        self.unstageButton = QtGui.QPushButton(self.Page1)
        self.unstageButton.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/unstage.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unstageButton.setIcon(icon1)
        self.unstageButton.setObjectName(_fromUtf8("unstageButton"))
        self.changesetButtonsLayout.addWidget(self.unstageButton)
        self.discardButton = QtGui.QPushButton(self.Page1)
        self.discardButton.setEnabled(False)
        self.discardButton.setObjectName(_fromUtf8("discardButton"))
        self.changesetButtonsLayout.addWidget(self.discardButton)
        self.separator = QtGui.QFrame(self.Page1)
        self.separator.setFrameShape(QtGui.QFrame.HLine)
        self.separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.separator.setObjectName(_fromUtf8("separator"))
        self.changesetButtonsLayout.addWidget(self.separator)
        self.pullButton = QtGui.QPushButton(self.Page1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/pull.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pullButton.setIcon(icon2)
        self.pullButton.setObjectName(_fromUtf8("pullButton"))
        self.changesetButtonsLayout.addWidget(self.pullButton)
        self.commitButton = QtGui.QPushButton(self.Page1)
        self.commitButton.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/commit_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commitButton.setIcon(icon3)
        self.commitButton.setObjectName(_fromUtf8("commitButton"))
        self.changesetButtonsLayout.addWidget(self.commitButton)
        self.stashButton = QtGui.QPushButton(self.Page1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/stash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stashButton.setIcon(icon4)
        self.stashButton.setObjectName(_fromUtf8("stashButton"))
        self.changesetButtonsLayout.addWidget(self.stashButton)
        self.pushButton = QtGui.QPushButton(self.Page1)
        self.pushButton.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/push.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.changesetButtonsLayout.addWidget(self.pushButton)
        self.horizontalLayout_4.addLayout(self.changesetButtonsLayout)
        self.files_listWidget = QtGui.QListWidget(self.Page1)
        self.files_listWidget.setObjectName(_fromUtf8("files_listWidget"))
        self.horizontalLayout_4.addWidget(self.files_listWidget)
        self.diff_textBrowser = QtGui.QTextBrowser(self.Page1)
        self.diff_textBrowser.setObjectName(_fromUtf8("diff_textBrowser"))
        self.horizontalLayout_4.addWidget(self.diff_textBrowser)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 3)
        self.changesetLayout.addLayout(self.horizontalLayout_4)
        self.bottomwidgets.addWidget(self.Page1)
        self.Page2 = QtGui.QWidget()
        self.Page2.setEnabled(True)
        self.Page2.setObjectName(_fromUtf8("Page2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.Page2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.changesetButtonsLayout_2 = QtGui.QVBoxLayout()
        self.changesetButtonsLayout_2.setObjectName(_fromUtf8("changesetButtonsLayout_2"))
        self.stageButton_2 = QtGui.QPushButton(self.Page2)
        self.stageButton_2.setEnabled(True)
        self.stageButton_2.setIcon(icon)
        self.stageButton_2.setObjectName(_fromUtf8("stageButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.stageButton_2)
        self.unstageButton_2 = QtGui.QPushButton(self.Page2)
        self.unstageButton_2.setEnabled(True)
        self.unstageButton_2.setIcon(icon1)
        self.unstageButton_2.setObjectName(_fromUtf8("unstageButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.unstageButton_2)
        self.discardButton_2 = QtGui.QPushButton(self.Page2)
        self.discardButton_2.setObjectName(_fromUtf8("discardButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.discardButton_2)
        self.separator_2 = QtGui.QFrame(self.Page2)
        self.separator_2.setFrameShape(QtGui.QFrame.HLine)
        self.separator_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.separator_2.setObjectName(_fromUtf8("separator_2"))
        self.changesetButtonsLayout_2.addWidget(self.separator_2)
        self.pullButton_2 = QtGui.QPushButton(self.Page2)
        self.pullButton_2.setIcon(icon2)
        self.pullButton_2.setObjectName(_fromUtf8("pullButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.pullButton_2)
        self.commitButton_2 = QtGui.QPushButton(self.Page2)
        self.commitButton_2.setEnabled(True)
        self.commitButton_2.setIcon(icon3)
        self.commitButton_2.setObjectName(_fromUtf8("commitButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.commitButton_2)
        self.stashButton_2 = QtGui.QPushButton(self.Page2)
        self.stashButton_2.setIcon(icon4)
        self.stashButton_2.setObjectName(_fromUtf8("stashButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.stashButton_2)
        self.pushButton_2 = QtGui.QPushButton(self.Page2)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.changesetButtonsLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addLayout(self.changesetButtonsLayout_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.Page2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.Unstaged_listwidget = QtGui.QListWidget(self.Page2)
        self.Unstaged_listwidget.setObjectName(_fromUtf8("Unstaged_listwidget"))
        self.verticalLayout_2.addWidget(self.Unstaged_listwidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.Page2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.Commit_textEdit = QtGui.QTextEdit(self.Page2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.Commit_textEdit.sizePolicy().hasHeightForWidth())
        self.Commit_textEdit.setSizePolicy(sizePolicy)
        self.Commit_textEdit.setObjectName(_fromUtf8("Commit_textEdit"))
        self.verticalLayout_3.addWidget(self.Commit_textEdit)
        self.label_2 = QtGui.QLabel(self.Page2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.Staged_listWidget = QtGui.QListWidget(self.Page2)
        self.Staged_listWidget.setObjectName(_fromUtf8("Staged_listWidget"))
        self.verticalLayout_3.addWidget(self.Staged_listWidget)
        self.verticalLayout_3.setStretch(3, 5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.bottomwidgets.addWidget(self.Page2)
        self.repositoryLayout.addWidget(self.bottomwidgets)
        self.repositoryLayout.setStretch(0, 8)
        self.repositoryLayout.setStretch(1, 7)
        self.horizontalLayout.addLayout(self.repositoryLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuRepository = QtGui.QMenu(self.menubar)
        self.menuRepository.setObjectName(_fromUtf8("menuRepository"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionClone_repository = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/clone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClone_repository.setIcon(icon6)
        self.actionClone_repository.setObjectName(_fromUtf8("actionClone_repository"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon7)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionAbout_PyGitGui = QtGui.QAction(MainWindow)
        self.actionAbout_PyGitGui.setObjectName(_fromUtf8("actionAbout_PyGitGui"))
        self.actionPull = QtGui.QAction(MainWindow)
        self.actionPull.setIcon(icon2)
        self.actionPull.setObjectName(_fromUtf8("actionPull"))
        self.actionAdd_files = QtGui.QAction(MainWindow)
        self.actionAdd_files.setObjectName(_fromUtf8("actionAdd_files"))
        self.actionRemove_files = QtGui.QAction(MainWindow)
        self.actionRemove_files.setObjectName(_fromUtf8("actionRemove_files"))
        self.actionCommit = QtGui.QAction(MainWindow)
        self.actionCommit.setIcon(icon3)
        self.actionCommit.setObjectName(_fromUtf8("actionCommit"))
        self.actionPush = QtGui.QAction(MainWindow)
        self.actionPush.setIcon(icon5)
        self.actionPush.setObjectName(_fromUtf8("actionPush"))
        self.actionChange_branch = QtGui.QAction(MainWindow)
        self.actionChange_branch.setObjectName(_fromUtf8("actionChange_branch"))
        self.actionCherry_pick = QtGui.QAction(MainWindow)
        self.actionCherry_pick.setObjectName(_fromUtf8("actionCherry_pick"))
        self.actionClone_repository_2 = QtGui.QAction(MainWindow)
        self.actionClone_repository_2.setIcon(icon6)
        self.actionClone_repository_2.setObjectName(_fromUtf8("actionClone_repository_2"))
        self.actionAdd_existing_repository = QtGui.QAction(MainWindow)
        self.actionAdd_existing_repository.setIcon(icon)
        self.actionAdd_existing_repository.setObjectName(_fromUtf8("actionAdd_existing_repository"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(dirname(__file__) + "/icons/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon8)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionAbout_Gitraffe = QtGui.QAction(MainWindow)
        self.actionAbout_Gitraffe.setObjectName(_fromUtf8("actionAbout_Gitraffe"))
        self.actionClone_repository_3 = QtGui.QAction(MainWindow)
        self.actionClone_repository_3.setIcon(icon6)
        self.actionClone_repository_3.setObjectName(_fromUtf8("actionClone_repository_3"))
        self.actionAdd_existing_repository_2 = QtGui.QAction(MainWindow)
        self.actionAdd_existing_repository_2.setIcon(icon)
        self.actionAdd_existing_repository_2.setObjectName(_fromUtf8("actionAdd_existing_repository_2"))
        self.actionStash = QtGui.QAction(MainWindow)
        self.actionStash.setIcon(icon4)
        self.actionStash.setObjectName(_fromUtf8("actionStash"))
        self.actionDelete_repository = QtGui.QAction(MainWindow)
        self.actionDelete_repository.setIcon(icon1)
        self.actionDelete_repository.setObjectName(_fromUtf8("actionDelete_repository"))
        self.actionDelete_branch = QtGui.QAction(MainWindow)
        self.actionDelete_branch.setObjectName(_fromUtf8("actionDelete_branch"))
        self.actionCreate_branch = QtGui.QAction(MainWindow)
        self.actionCreate_branch.setObjectName(_fromUtf8("actionCreate_branch"))
        self.menuFile.addAction(self.actionClone_repository_2)
        self.menuFile.addAction(self.actionAdd_existing_repository)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionRefresh)
        self.menuRepository.addAction(self.actionPull)
        self.menuRepository.addAction(self.actionCommit)
        self.menuRepository.addAction(self.actionStash)
        self.menuRepository.addAction(self.actionPush)
        self.menuRepository.addSeparator()
        self.menuRepository.addAction(self.actionChange_branch)
        self.menuRepository.addAction(self.actionDelete_branch)
        self.menuRepository.addAction(self.actionCreate_branch)
        self.menuHelp.addAction(self.actionAbout_Gitraffe)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuRepository.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionClone_repository_3)
        self.toolBar.addAction(self.actionAdd_existing_repository_2)
        self.toolBar.addAction(self.actionDelete_repository)

        self.retranslateUi(MainWindow)
        self.bottomwidgets.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Gitraffe", None, QtGui.QApplication.UnicodeUTF8))
        item = self.repositoryTableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Commit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.repositoryTableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Message", None, QtGui.QApplication.UnicodeUTF8))
        item = self.repositoryTableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        item = self.repositoryTableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.stageButton.setText(QtGui.QApplication.translate("MainWindow", "Stage", None, QtGui.QApplication.UnicodeUTF8))
        self.unstageButton.setText(QtGui.QApplication.translate("MainWindow", "Unstage", None, QtGui.QApplication.UnicodeUTF8))
        self.discardButton.setText(QtGui.QApplication.translate("MainWindow", "Discard", None, QtGui.QApplication.UnicodeUTF8))
        self.pullButton.setText(QtGui.QApplication.translate("MainWindow", "Pull", None, QtGui.QApplication.UnicodeUTF8))
        self.commitButton.setText(QtGui.QApplication.translate("MainWindow", " Commit", None, QtGui.QApplication.UnicodeUTF8))
        self.stashButton.setText(QtGui.QApplication.translate("MainWindow", "Stash", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Push", None, QtGui.QApplication.UnicodeUTF8))
        self.stageButton_2.setText(QtGui.QApplication.translate("MainWindow", "Stage", None, QtGui.QApplication.UnicodeUTF8))
        self.unstageButton_2.setText(QtGui.QApplication.translate("MainWindow", "Unstage", None, QtGui.QApplication.UnicodeUTF8))
        self.discardButton_2.setText(QtGui.QApplication.translate("MainWindow", "Discard", None, QtGui.QApplication.UnicodeUTF8))
        self.pullButton_2.setText(QtGui.QApplication.translate("MainWindow", "Pull", None, QtGui.QApplication.UnicodeUTF8))
        self.commitButton_2.setText(QtGui.QApplication.translate("MainWindow", " Commit", None, QtGui.QApplication.UnicodeUTF8))
        self.stashButton_2.setText(QtGui.QApplication.translate("MainWindow", "Stash", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Push", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Unstaged:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Commit message:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Staged:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRepository.setTitle(QtGui.QApplication.translate("MainWindow", "Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClone_repository.setText(QtGui.QApplication.translate("MainWindow", "Clone repository...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_PyGitGui.setText(QtGui.QApplication.translate("MainWindow", "About PyGitGui", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPull.setText(QtGui.QApplication.translate("MainWindow", "Pull", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_files.setText(QtGui.QApplication.translate("MainWindow", "Add files...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_files.setText(QtGui.QApplication.translate("MainWindow", "Remove files...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCommit.setText(QtGui.QApplication.translate("MainWindow", "Commit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPush.setText(QtGui.QApplication.translate("MainWindow", "Push", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_branch.setText(QtGui.QApplication.translate("MainWindow", "Change branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCherry_pick.setText(QtGui.QApplication.translate("MainWindow", "Cherry-pick", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClone_repository_2.setText(QtGui.QApplication.translate("MainWindow", "Clone repository...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_existing_repository.setText(QtGui.QApplication.translate("MainWindow", "Add existing repository...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Gitraffe.setText(QtGui.QApplication.translate("MainWindow", "About Gitraffe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClone_repository_3.setText(QtGui.QApplication.translate("MainWindow", "Clone repository...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_existing_repository_2.setText(QtGui.QApplication.translate("MainWindow", "Add existing repository", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStash.setText(QtGui.QApplication.translate("MainWindow", "Stash", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_repository.setText(QtGui.QApplication.translate("MainWindow", "Delete repository", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_branch.setText(QtGui.QApplication.translate("MainWindow", "Delete branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_branch.setText(QtGui.QApplication.translate("MainWindow", "Create branch", None, QtGui.QApplication.UnicodeUTF8))

